export const charge_type = [
  { id: 1, name: "Charge Type", value: "No assigned" },
  { id: 2, name: "Appraisal Cost", value: "Appraisal Cost" },
  { id: 3, name: "Auctioneer Cost", value: "Auctioneer Cost" },
  { id: 4, name: "Coverage Attorney", value: "Coverage Attorney" },
  { id: 5, name: "Document Cost", value: "Document Cost" },
  { id: 6, name: "Filing Cost", value: "Filing Cost" },
  { id: 7, name: "Guardian Ad Litem", value: "Guardian Ad Litem" },
  { id: 8, name: "Lien Search", value: "Lien Search" },
  { id: 9, name: "Local Counsel", value: "Local Counsel" },
  { id: 10, name: "Mediation Cost", value: "Mediation Cost" },
  { id: 11, name: "Movers Cost", value: "Movers Cost" },
  { id: 12, name: "Notice Of Action", value: "Notice Of Action" },
  { id: 13, name: "O/N Service", value: "O/N Service" },
  { id: 14, name: "Postage Cost", value: "Postage Cost" },
  { id: 15, name: "Posting Of Nod Cost", value: "Posting Of Nod Cost" },
  {
    id: 16,
    name: "Posting Of Postponement Cost",
    value: "Posting Of Postponement Cost",
  },
  { id: 17, name: "Publication Of Nod", value: "Publication Of Nod" },
  {
    id: 18,
    name: "Publication Of Notice Of Sale",
    value: "Publication Of Notice Of Sale",
  },
  { id: 19, name: "Sale Fee Cost", value: "Sale Fee Cost" },
  { id: 20, name: "Service Of Process Cost", value: "Service Of Process Cost" },
  {
    id: 21,
    name: "Sheriff Fee / Comission Cost",
    value: "Sheriff Fee / Comission Cost",
  },
  { id: 22, name: "Sheriff Process Cost", value: "Sheriff Process Cost" },
  { id: 23, name: "Sheriff Sale Cost", value: "Sheriff Sale Cost" },
  { id: 24, name: "Skip Trace", value: "Skip Trace" },
  { id: 25, name: "Special Rep Cost", value: "Special Rep Cost" },
  { id: 26, name: "Title Policy Cost", value: "Title Policy Cost" },
  { id: 27, name: "Title Search / Title Update", value: "Title Search / Title Update" },
  { id: 28, name: "Other", value: "Other" },
];

export const document_type = [
  { id: 1, name: "Document Type", value: "No assigned" },
  { id: 2, name: "Ad Litem Invoice", value: "Ad Litem Invoice" },
  { id: 3, name: "Appraisal Invoice", value: "Appraisal Invoice" },
  { id: 4, name: "Auctioneer Invoice", value: "Auctioneer Invoice" },
  {
    id: 5,
    name: "Coverage Attorney Invoice",
    value: "Coverage Attorney Invoice",
  },
  { id: 6, name: "Doc Retrieval Invoice", value: "Doc Retrieval Invoice" },
  { id: 7, name: "Examiner Recording", value: "Examiner Recording" },
  { id: 8, name: "Gap Check", value: "Gap Check" },
  { id: 9, name: "Local Counsel Invoice", value: "Local Counsel Invoice" },
  { id: 10, name: "Mediation Invoice", value: "Mediation Invoice" },
  { id: 11, name: "Movers Invoice", value: "Movers Invoice" },
  {
    id: 12,
    name: "Sale Publication Invoice",
    value: "Sale Publication Invoice",
  },
  { id: 13, name: "Service Process Invoice", value: "Service Process Invoice" },
  { id: 14, name: "Skip Trace Invoice", value: "Skip Trace Invoice" },
  { id: 15, name: "Special Rep Invoice", value: "Special Rep Invoice" },
  { id: 16, name: "Title Policy", value: "Title Policy" },
  {
    id: 17,
    name: "Title Search / Update Invoice",
    value: "Title Search / Update Invoice",
  },
  { id: 18, name: "Vendor Correspondence", value: "Vendor Correspondence" },
  { id: 19, name: "Other", value: "Other" },
];

export const confirmation_number = [
  { id: 1, name: "Confirmation #", value: "No assigned" },
  { id: 2, name: "Ad Id Number", value: "Ad Id Number" },
  { id: 3, name: "Ad Number", value: "Ad Number" },
  { id: 4, name: "AMEX", value: "AMEX" },
  { id: 5, name: "Date + Last Name", value: "Date + Last Name" },
  { id: 6, name: "File Number", value: "File Number" },
  { id: 7, name: "Invoice Number", value: "Invoice Number" },
  { id: 8, name: "Legal Number", value: "Legal Number" },
  { id: 9, name: "Order Number", value: "Order Number" },
  { id: 10, name: "Our File Number", value: "Our File Number" },
  { id: 11, name: "Reference Number", value: "Reference Number" },
  { id: 12, name: "Transaction Number", value: "Transaction Number" },
  { id: 13, name: "Other", value: "Other" },
];
